language: generic
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::1}
  - REPO=haraldkoch/jenkins-slave

script: docker build -f Docketfile -t $REPO:$COMMIT .

after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
